# Generated by Django 6.0.6 on 2026-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ai_category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='ai_priority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='todo',
            name='best_time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('any', 'Any')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='last_ai_analysis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='preferred_weather',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='weather_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
